### PR TITLE
Start listeners manually in bootstrap

### PR DESCRIPTION
**Pull request by MayGo**

### CODE REVIEW

**Comment by svene** [comment]
I would be interested in this functionality as well. Is someone still working on this this PR?

**Comment by froilan** [comment]
@MayGo 
Hi, keen to have this functionality. 
Any reason why this is not yet merged?

**Comment by jeffbrown** [comment]
@froilan This plugin is in need of a shepherd.  Are you interested in helping with that?

**Comment by froilan** [comment]
@jeffbrown 
Sure, we need it anyways. What needs to be done?

**Comment by jeffbrown** [comment]
@MayGo Made the change.  Are you interested in being added as a collaborator and helping to maintain the plugin?

**Comment by froilan** [comment]
@jeffbrown 
Alright.

**Pull request closed without merging**
