### PR TITLE
Support autoStartup

### PR DESCRIPTION
**Pull request by jonspalmer**
This fix addresses the bug described in http://jira.grails.org/browse/GPJMS-15. 

The plugin incorrectly starts the listeners in all cases. In fact the autoStartup property controls this already for us so I just removed the 'start' code altogether.

### CODE REVIEW

**Comment by rblazquez** [comment]
I am experiencing the same http://jira.grails.org/browse/GPJMS-15. issue.

Is this problem fixed?

Sorry to ask but the pull request history looks confusing.

**Comment by froilan** [comment]
@alkemist @berngp @bostanio 
Hi guys, sorry to ask, just wondering why this is not merged yet.
The issue still occurs.

**Comment by alkemist** [comment]
@froilan we are no longer maintaining this code. I suggest forking it and applying the changes.

**Comment by sbglasius** [comment]
Outdated. Closing it.

**Pull request closed without merging**
