### PR TITLE
Support Grails 3.2.0

### PR DESCRIPTION
**Pull request by andrebrov**
I did migration from scratch using recommendations from grails documentation.

### CODE REVIEW

**Comment by puneetbehl** [comment]
Just FYI, that there is already a branch 2.0.x which seems to be Grails 3 version. But, I am not aware of the current state.

**Comment by puneetbehl** [comment]
Also, it seems like Grails 3 version is already available http://grails.org/plugins.html#plugin/jms

**Comment by andrebrov** [comment]
@puneetbehl branch 2.0.x is not working with grails 3.2.0 and link you provided leads to 404 https://github.com/grails3-plugins/jms

**Comment by graemerocher** [comment]
@andrebrov the code is here https://github.com/gpc/jms/tree/2.0.x

**Comment by puneetbehl** [comment]
Also, not sure why the link I shared is http://grails.org/plugins.html#plugin/jms but the one you are sharing is different. Still, if you are not able to find then please goto:

- http://grails.org/plugins.html
_ Search for jms

I hope you should be able to find the plugin. And for 2.0.x branch then please report the issue you are facing.

**Comment by puneetbehl** [comment]
My bad just saw the [issue](https://github.com/gpc/jms/issues/24)

**Comment by sbglasius** [comment]
It seems that this is obsolete. Objections if I close this PR?

**Comment by sbglasius** [comment]
Apparently no objections, so closing this PR

**Pull request closed without merging**
